### ISSUE TITLE
Viewfinder incorrect on Pixel 8 Pro with Android 15 DP1

### ISSUE THREAD

**Issue by JolandaVerhoef** [google/jetpack-camera-app#141]
There's a regression of the viewfinder behavior when using an Android 15 device.

Emulator Android 15:
<img src="https://github.com/google/jetpack-camera-app/assets/6952116/c36b5a60-a537-4adc-a241-d017f9ffd47b" width=200/>

Emulator Android 14:
<img src="https://github.com/google/jetpack-camera-app/assets/6952116/1fd512ed-3898-46b2-8b1e-0c0b782e662d" width=200/>

Some remarks:
- Verified the same behavior on physical devices, comparing Pixel 7 Pro with Android 14 (working) to Pixel 8 Pro with Android 15 DP1 (not working).
- Video capture result has the right dimensions, so the issue is really in the viewfinder part.

**Comment by JolandaVerhoef** [comment]
Fixed with DP2!

**Comment by Sk8aaron** [comment]
wow, looks similar to this issue: https://github.com/google/jetpack-camera-app/issues/207#issue-2309760398
viewfinder might be need a fix.
