### ISSUE TITLE
CI tests failing because tasks cannot be found

### ISSUE THREAD

**Issue by temcguir** [google/jetpack-camera-app#235]
See [this build report](https://github.com/google/jetpack-camera-app/actions/runs/9601687551/job/26480788021) as an example. After #216 was added, CI has started to fail with the following errors:

```
Task 'pixel2Api28DebugAndroidTest' not found in root project 'Jetpack Camera' and its subprojects.
```
and
```
Task 'pixel8Api34DebugAndroidTest' not found in root project 'Jetpack Camera' and its subprojects.
```

This seems to be due to the addition of flavors. For instance, `pixel8Api34StableDebugAndroidTest` works locally. We may need to figure out if there's a way to make `pixel8Api34DebugAndroidTest` still trigger the default flavor (Stable) or if we need to change CI to adjust the task names.

**Comment by Jaehwa-Noh** [comment]
The task name is associated with a flavor name, so that we might seemingly change the task name to `pixel8Api34StableDebugAndroidTest` in CI.

Is it also need to test preview version UI tests on CI?
