### ISSUE TITLE
Preview stream freezes when switching aspect ratio via quick settings

### ISSUE THREAD

**Issue by temcguir** [google/jetpack-camera-app#67]
Setting the aspect ratio via the quick settings (drop-down arrow at the top of the screen) causes the preview stream to freeze.

This is 100% reproducible on the Pixel 7 Pro.

This seems to have been caused by [PR#64](https://github.com/google/jetpack-camera-app/pull/64). Reverting that change causes the issue to go away.

**Comment by kailianc** [comment]
Looking into the issue.

**Comment by kailianc** [comment]
The root cause is surfaceProvider is not set when updating usecases.
The issue will be fixed in: https://github.com/google/jetpack-camera-app/pull/68
